### ISSUE TITLE
Add to OpenVSX

### ISSUE THREAD

**Issue by BuzzwordChief** [konapun/vscode_all-hallows-eve-plus#2]
Hey, 
loving the theme, great work. Could you consider adding it to open-vsx.org? It's an alternative source for vscode extensions used by free vscode alternatives like vscodium, onivim2...

Would do it myself if you add a licence to the project :)

**Comment by konapun** [comment]
Hi, @BuzzwordChief,

I just added a MIT license so feel free to do whatever you'd like with it!
